### ISSUE TITLE
does not recurse upwards in path hierarchy

### ISSUE THREAD

**Issue by Bengreen** [tunnckoCore/get-installed-path#11]
i tried this out and it is working fine when I know exactly the path of the node_modules and can specify this in cwd, but it seems to be missing the option to search through the hierarchy of paths form the cwd to find the different node_modules directories that could be used for installation. e.g. in node: the process object has a mainModule.paths which has an array of the possible install paths to search).

If this is possible already can you point me to the way to do this ?

**Comment by tunnckoCore** [comment]
Probably should add option for changing that, it's hardcoded [in that line](https://github.com/tunnckoCore/get-installed-path/blob/master/index.js#L153)

**Comment by Bengreen** [comment]
i did a wrapper around getInstalledPath to allow me to do the hierarchical check on the array (it is messy, but works... maybe it is useful to help you get the functionality into the library itself).

```javascript
function modPathFromArray(moduleName, pathArray) {
    return pathArray.reduce((acc, val) => {
        if (!acc) {
            try {
                var temp = getInstalledPath.sync(moduleName, {
                    local: true,
                    cwd: val
                });
                console.log("found it at :", val);
                console.log("it was :", temp);
                return temp;
            } catch (err) {
                // console.log("did not find path at :", val);
                return acc;
            };
        }
        return acc;
    }, "");
}


var npmPath = process.mainModule.paths;
var npmRootPath = npmPath.map((pathVal) => pathVal.slice(0, -13));

var webPackDir = modPathFromArray('webpack', npmRootPath);
```
