### ISSUE TITLE
Consider deprecating this module

### ISSUE THREAD

**Issue by mik01aj** [tunnckoCore/get-installed-path#3]
We had problems with it in https://github.com/sapegin/react-styleguidist/issues/59 and realized that it has problems when it is used from a dependency `B` of some other module `A`, because then it can't find the locally-installed package `C` (in `A/node_modules/B/node_modules/C`, when installed with npm 2.x), because `process.pwd()` is `/path/to/A`.

And it seems to me that the use case of finding an installed module is better served by [`require.resolve(...)`](https://nodejs.org/api/modules.html). Correct?

**Comment by tunnckoCore** [comment]
Hm. Maybe.. But not.
There's still have few use cases. 
One is that you can control what directory you want with second argument - I mean local/global directory of wanted module. Second, this module always returns only path to module directory, not path to file or etc.

Is this clarify a bit the differences between them? Or.. i'm wrong, i'll review this weekend.

Sorry if have mistakes or something, I'm after party.
- Cheers, :beer:

**Comment by mik01aj** [comment]
Well, if you want to keep this module, I encourage you to: 
1. Tell people in README that they might not need this module because there's `require.resolve(...)`
2. Warn them about the quirks with deps-of-deps in npm 2.x (because in these situations `get-installed-path` can't find the right path, whereas requiring the module works)
3. Consider returning null instead of empty string when the module is not found.

**Comment by tunnckoCore** [comment]
@mik01aj There are differences. This package gives you directory name of the given package. Also it works for global and local packages. `require.resolve` works for local only. `require.resolve` gives you the main of the package.

Let me know if recent major bump fix your case or not. In anyway it is not for deprecation. It will be the core behind "hybrid/universal resolver" (maybe `resolve-package` :)) - you gives a package name, it looks locally, then if not found, looks on global. There's already one `resolve-pkg` but it not does my thing and need.

**Comment by mik01aj** [comment]
I can't give you much feedback, I switched jobs and don't use it anymore. I guess a mention of `require.resolve` in the README would be nice anyway :)
